name: kueski_movies_app
description: "See what movies are in trending for Kueski"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6

  envied: ^0.5.3 #used for .env files
  
  freezed_annotation: ^2.4.1  #creates bolierplate code
  
  flutter_bloc: ^8.1.4  # event to state management
  flutter_hooks: ^0.20.5 #hooks for Flutter
  dartz: ^0.10.1  #parsing responses 
  kt_dart: ^1.1.0  #lists as ktlists
  injectable: ^2.3.2   #dependency injection
  get_it: ^7.6.7   #dependency injection generation 


  go_router: ^13.2.1  #routing

  localstore: ^1.3.5
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  injectable_generator: ^2.4.1
  freezed: ^2.4.7 
  build_runner: ^2.4.8


flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

